topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6450
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 7400
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2400
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10150
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 12900

jobs:
  389ds-fedora/test_topology_TestTopologyOptions:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'spichugi/preformance_test'
        test_suite: test_integration/test_topology.py::TestTopologyOptions
        template: *ci-master-latest
        timeout: 7200
        topology: *master_3repl_1client
